_core:
  default_config_hash: rpfRQVoEn2ZWd_lw-iULKPiuina5CqcmzXWlz1OjTwM
name: boston.gov
mail: website@boston.gov
simple_address: false
sitestyle: true
textonly: false
linkonly: false
user_plaintext_field: ''
format: html_email
preserve_class: false
advanced:
  incoming: false
  key: luTHSt9ITPyjhUKT23lDrTBI_TKvJ47MXZCXQfmvKQw
