module:
  automated_cron: 0
  acquia_connector: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  autologout: 0
  ban: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  chosen: 0
  chosen_lib: 0
  color: 0
  comment: 0
  config: 0
  config_devel: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  cors: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  field: 0
  field_collection: 0
  field_group: 0
  field_group_migrate: 0
  field_ui: 0
  file: 0
  file_entity: 0
  filter: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  imce: 0
  link: 0
  linkit: 0
  login_security: 0
  media: 0
  metatag: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  migrate_plus: 0
  migrate_tools: 0
  migrate_upgrade: 0
  module_filter: 0
  node: 0
  office_hours: 0
  options: 0
  page_cache: 0
  paragraphs_type_permissions: 0
  path: 0
  phpexcel: 0
  purge: 0
  purge_queuer_coretags: 0
  quickedit: 0
  rabbit_hole: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  rh_file: 0
  rh_taxonomy: 0
  rules: 0
  salesforce: 0
  search: 0
  seckit: 0
  shortcode: 0
  shortcut: 0
  stage_file_proxy: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  token_custom: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  typed_data: 0
  update: 0
  user: 0
  viewfield: 0
  views_ui: 0
  workbench: 0
  workbench_moderation: 0
  workflows: 0
  xmlsitemap: 0
  xmlsitemap_engines: 0
  menu_link_content: 1
  views: 10
  paragraphs: 11
theme:
  adminimal_theme: 0
  bos_theme: 0
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
profile: bos_profile
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
