_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - bos_city_score.settings
  - bos_core.settings
  - bos_emergency_alerts.settings
  - bos_mnl.settings
  - bos_swiftype.settings
  - 'core.entity_view_display.node.metrolist_development.*'
  - geolocation_google_maps.settings
  - 'paragraphs.paragraphs_type.*:dependencies.content|icon_uuid'
  - purge.logger_channels
  - salesforce.salesforce_auth.dnd_prod
  - salesforce.salesforce_auth.moh_fullcopy_sandbox
  - salesforce.settings
  - slackposter.settings
  - node_elections.settings
  - block.block.website_feedback_form

